### ISSUE TITLE
Usage with trunk?

### ISSUE THREAD

**Issue by iMplode-nZ** [GoogleChromeLabs/wasm-bindgen-rayon#11]
Trunk is a rust application bundler: https://trunkrs.dev/. It isn't clear how to use trunk with this.

**Comment by RReverser** [comment]
> It isn't clear how to use trunk with this.

To me either, I never used it. If you know how to use them together, PRs to documentation are welcome.

Or maybe it even should be documented on their side?

**Comment by iMplode-nZ** [comment]
I think it makes more sense to document it on this side as bundlers cannot reasonably document how to use every library (many more libraries than bundlers).

I'll try to figure out how to use this with trunk and then send a PR.

**Comment by RReverser** [comment]
> as bundlers cannot reasonably document how to use every library 

No, but they might want to document how to use multithreading, and so far this is one of very few days to use it in Rust (and the only that works with majority of existing Rayon-based ecosystem).

**Comment by iMplode-nZ** [comment]
Fair point, it actually might make sense for bundlers to have something like this built in as an optional feature.

**Comment by RReverser** [comment]
> Fair point

To be clear, I'm happy if it's documented on both sides too. It's just that, if there's a bundler designed _specifically_ for Rust+Wasm, it seems like a good idea for it to have its own multithreading docs as well to save its users some time.

**Comment by RReverser** [comment]
I guess I'll close this issue for now. Any improvements to docs are welcome in PRs.

**Comment by iMplode-nZ** [comment]
Thanks (also I'm using `trunk watch` and a custom server)
but I'm not using this as it doesn't support transfering javascript objects across workers.

**Comment by RReverser** [comment]
>  but I'm not using this as it doesn't support transfering javascript objects across workers.

Nothing would, it's an inherent limitation of JavaScript Workers. You can either use JS APIs directly in the worker environment where possible, or `postMessage` values from the main thread.

I guess `postMessage` itself could be wrapped into some Rust-y API and published as a separate crate though. Could be an interesting experiment to model it as a `Cell`-like API where you can put a JS value into it on any thread, and asynchronously read from another.

**Comment by iMplode-nZ** [comment]
Yeah that's exactly what I'd like

**Comment by iMplode-nZ** [comment]
The thing is I think such a feature would need to be integrated directly into the rust web worker system itself.

**Comment by RReverser** [comment]
> would need to be integrated directly into the rust web worker system itself.

Hmm I'm not so sure, I think you could instead introduce some sort of `Messenger` trait and implement on relevant web-sys types - Window, WorkerGlobalScope, etc. and have that custom `MessageCell` type accept generic `M: Messenger` to integrate with whatever channel user wants.

It could be interesting to experiment with this, hard to tell how complicated it would be until someone tries to design it.

**Comment by RReverser** [comment]
Ah, in case of `Worker` I guess you're right that it needs to be integrated, because the cell would need to be able to access `worker` objects and subscribe to `worker.onmessage` event.

In that case maybe it is worth designing it on top of wasm-bindgen-rayon.

**Comment by RReverser** [comment]
Nvm, I just remembered - even `onmessage` wouldn't work because Rayon never returns to the JS event loop, it blocks Workers synchronously, so you can't share JS values at all.

**Comment by iMplode-nZ** [comment]
Perhaps rayon-like but async could work? Like you could make an async executor instead...

**Comment by RReverser** [comment]
At that point you probably want [wasm-mt](https://github.com/w3reality/wasm-mt) instead.

**Comment by iMplode-nZ** [comment]
The issue is wasm-mt doesn't support shared memory at all, which makes it pretty much useless as everything has to go through JavaScript.
