### ISSUE TITLE
How to use javascript primitives.

### ISSUE THREAD

**Issue by iMplode-nZ** [GoogleChromeLabs/wasm-bindgen-rayon#14]
I would like to use `OffscreenCanvas` in a task, but it isn't `Send`.

**Comment by RReverser** [comment]
Sorry this is way too generic question. Is there a sample of code that isn't working? Are you sure it's a bug in wasm-bindgen-rayon?

If it's a general question, StackOverflow might be a better place than an issue tracker.

If it's an issue with web-sys bindings, their repo might be a better place for a bug.

**Comment by ImUrX** [comment]
@iMplode-nZ OffscreenCanvas should be made in each thread

**Comment by RReverser** [comment]
Sorry but I'm going to close this as this issue tracker is for bug reports and feature requests to wasm-bindgen-rayon itself, while the question doesn't seem to fall into that category.

**Comment by iMplode-nZ** [comment]
@RReverser Just FYI, it seems like the issue tracker is also used in quite a few repositories for questions as well.

**Comment by RReverser** [comment]
> it seems like the issue tracker is also used in quite a few repositories for questions as well

Sometimes, maybe, but most OSS maintainers aren't too happy about that as it makes it harder to track actual bugs. That's also the reason why Github recently introduced a dedicated Discussions feature to split those up (but IMO StackOveflow is still more convenient / conventional).
