### ISSUE TITLE
RuntimeError: Atomics.wait cannot be called in this context

### ISSUE THREAD

**Issue by ArchitBhonsle** [GoogleChromeLabs/wasm-bindgen-rayon#18]
For some reason, `initThreadPool` seems to be giving this error. I am using the `no-bundler` feature with a simple go server.

```
Uncaught (in promise) RuntimeError: Atomics.wait cannot be called in this context
    at core::core_arch::wasm32::atomic::memory_atomic_wait32::h9a9a231b6412c421 (linalg_bg.wasm:0x94e305)
    at std::sys::wasm::mutex::Mutex::lock::h0477dcfe8d39c9ec (linalg_bg.wasm:0x717f9f)
    at std::sys_common::mutex::MovableMutex::raw_lock::h74885940bb867605 (linalg_bg.wasm:0x94bd5d)
    at std::sync::mutex::Mutex<T>::lock::hdd7beaa199985733 (linalg_bg.wasm:0x933c13)
    at spmc::channel::Sender<T>::send::h99ef43bb4692506c (linalg_bg.wasm:0x238560)
    at wasm_bindgen_rayon::wbg_rayon_PoolBuilder::build::{{closure}}::hdce48bcd346070a5 (linalg_bg.wasm:0x613768)
    at <rayon_core::registry::CustomSpawn<F> as rayon_core::registry::ThreadSpawn>::spawn::h986960739e3987c9 (linalg_bg.wasm:0x4eb03d)
    at rayon_core::registry::Registry::new::h28bbaa87b0a093f6 (linalg_bg.wasm:0x8221a)
    at rayon_core::registry::init_global_registry::{{closure}}::hfde6a4e256abdcae (linalg_bg.wasm:0x68e9a8)
    at rayon_core::registry::set_global_registry::{{closure}}::hd1d3fb73eb496efa (linalg_bg.wasm:0x584915)
```

Here's the html.
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>linalg demo</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <script type="module">
    import init, {initThreadPool} from './../pkg/linalg.js';

    (async () => {
      await init();
      await initThreadPool(navigator.hardwareConcurrency);
    })()
  </script>
</body>

</html>
```

And here's my server
```go
package main

import (
	"fmt"
	"net/http"
)

func addHeaders(handler http.Handler) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cross-Origin-Opener-Policy", "same-origin")
		w.Header().Set("Cross-Origin-Embedder-Policy", "require-corp")

		handler.ServeHTTP(w, r)
	}
}

func main() {
	fsHandler := http.FileServer(http.Dir("./"))
	http.Handle("/", addHeaders(fsHandler))

	fmt.Println("🚀 Listening on http://localhost:5000/")
	http.ListenAndServe(":5000", nil)
}
```

I also tried it with `vite` and without the `no-bundler` feature and getting the same error. Is there some configuration for `wasm-bindgen`, `wasm-pack` and `wasm-bidngen-rayon` that just works?

**Comment by RReverser** [comment]
The [Caveats](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon#caveats) section near the top of docs specifically describes this:

> Most notably, even when you're using multithreading, the main thread still can't be blocked while waiting for the Rayon pool to get ready or for all the background operations to finish.
>
> You must instantiate the main JS+Wasm in a dedicated Worker to avoid blocking the main thread - that is, don't mix UI and Rayon code together. Instead, use a library like Comlink or a custom glue code to expose required wasm-bindgen methods to the main thread, and do the UI work from there.

**Comment by ArchitBhonsle** [comment]
I did try this:

Here's my `main.js`
```js
import init, {
  initThreadPool,
} from '@ml.wasm/linalg';

import * as Comlink from "comlink";

async function executeOnWorker(f) {
  const remoteFunction = Comlink.wrap(new Worker(new URL("./worker.js", import.meta.url)));
  await remoteFunction(Comlink.proxy(f));
}

async function initialize() {
  console.log('inits started');

  await init();
  await initThreadPool(navigator.hardwareConcurrency);

  console.log('inits performed');
}
executeOnWorker(initialize);
```
and here's the `worker.js`:
```js
importScripts("../node_modules/comlink/dist/umd/comlink.js");

async function remoteFunction(cb) {
  await cb();
}

Comlink.expose(remoteFunction);
```

This gives the same error.

I also tried doing the inits on the worker but that would mean doing the following in a worker:
```js
importScripts("../node_modules/@ml.wasm/linalg/linalg.js");
```
which in turn gives this error:
```
Uncaught SyntaxError: Cannot use import statement outside a module
    at worker.js:2
```
which is caused by the first line of `linalg.js`:
```js
import { startWorkers } from '/node_modules/@ml.wasm/linalg/snippets/wasm-bindgen-rayon-7afa899f36665473/src/workerHelpers.js';
```

Am I missing something really obvious?

**Comment by ArchitBhonsle** [comment]
Also this is why I did the initializations on the main thread:
![image](https://user-images.githubusercontent.com/34616931/140317577-c61c3e7e-9ce0-40bc-a0bd-86ac73525bc9.png)

**Comment by RReverser** [comment]
> Also this is why I did the initializations on the main thread:

Right, the wording there could certainly be improved. It's hard to convey difference between "main thread" as in "main thread from PoV of Rust code" vs "main thread" as in "browser main thread used for UI work".

What that comment meant is that `init` & `initThreadPool` need to be invoked from main thread from Rust PoV, even though it actually lives in the worker as per caveats.

It might be helpful to also look at the demo code which invokes those functions in a worker file: https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/blob/5f54573052ea70986e1d23d3ebe876702c671335/demo/wasm-worker.js#L31-L32

**Comment by RReverser** [comment]
> I also tried doing the inits on the worker but that would mean doing the following in a worker:
> 
> ```js
> importScripts("../node_modules/@ml.wasm/linalg/linalg.js");
> ```

You can use [module workers](https://web.dev/module-workers/) instead, that is, use regular `import` in the Worker and instantiate it with `type: 'module'`.

**Comment by ArchitBhonsle** [comment]
Yup my bad. Somehow missed the `demo`. Works as expected!

**Comment by RReverser** [comment]
Glad to hear! Be sure to watch out for lack of module Workers support in Firefox if you use no-bundler mode (in that case, you need to include polyfill): https://github.com/GoogleChromeLabs/wasm-bindgen-rayon#usage-without-bundlers

**Comment by RReverser** [comment]
> Right, the wording there could certainly be improved. It's hard to convey difference between "main thread" as in "main thread from PoV of Rust code" vs "main thread" as in "browser main thread used for UI work".

Btw, I'm serious - I don't want others to stumble upon this like you did. If you have ideas on how to improve the wording so that it's clearer, I'm happy to accept PRs :)
