### ISSUE TITLE
Integration with React

### ISSUE THREAD

**Issue by yuichiroaoki** [GoogleChromeLabs/wasm-bindgen-rayon#19]
Hi, thank you for this amazing work. 

I'm trying to use it with my create react app by following the instructions in the readme, but I came across this bug. 
I'm using [craco](https://github.com/gsoft-inc/craco) and [wasm-loader](https://github.com/ballercat/wasm-loader) to override the default webpack config of create-react-app.

```
./node_modules/wasm-pkg/wasm_bg.wasm
Module parse failed: Unexpected section: 0xc
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: Unexpected section: 0xc
```

![image](https://user-images.githubusercontent.com/45054071/145354608-d34575b9-6864-4fb0-a98f-04987b279b6d.png)

## Step to reproduce
```bash
git clone https://github.com/yuichiroaoki/react-wasm.git
cd react-wasm
yarn install
yarn start
```
[repo](https://github.com/yuichiroaoki/react-wasm)

I have included wasm pkg into the repo so that you have the same one.

Does wasm-bindgen-rayon work with a single page app like create react app or am I setting the config wrong ??

Thanks for your help.

**Comment by RReverser** [comment]
I don't know, sounds like a problem with wasm-loader or something else trying to parse modern Wasm with threads.

Given that the link you provided (https://github.com/ballercat/wasm-loader) says that repo is archived and loader is deprecated, most likely it's just out of date.

**Comment by yuichiroaoki** [comment]
Thank you very much for your quick reply!

I see. That's right.
I'm going to upgrade my CRA.
