### ISSUE TITLE
`init_thread_pool(0)` will freeze the worker with no error

### ISSUE THREAD

**Issue by zxch3n** [GoogleChromeLabs/wasm-bindgen-rayon#20]
# Expected behavior

Switching to optimal thread number or throwing an error.

**Comment by RReverser** [comment]
Adding an error makes sense, but I wonder how/why did you pass `0` in real-world code.

**Comment by zxch3n** [comment]
I thought the behavior would be the same as [Rayon's num_threads API](https://docs.rs/rayon/latest/rayon/struct.ThreadPoolBuilder.html#method.num_threads). 

> If num_threads is 0, or you do not call this function, then the Rayon runtime will select the number of threads automatically. At present, this is based on the RAYON_NUM_THREADS environment variable (if set), or the number of logical CPUs (otherwise).

And many other thread-related APIs also use 0 or -1 to select the number of threads automatically. No idea whether it's possible in the browser context though. 

This behavior can be learned during development, but document or error messages can be very helpful.

And thanks for this tool! It's really amazing.

**Comment by RReverser** [comment]
Ah interesting.

I kind of wanted to keep number of threads manual to make sure that users don't get code bloat from automatic detection, so for now I'm leaning towards making this a clear error.

Need to check how to do it without also significant code bloat though.

**Comment by RReverser** [comment]
If you want to send a PR to add such error, that would be welcome too btw.

**Comment by zxch3n** [comment]
Ok, I'll submit a PR~
