### ISSUE TITLE
initThreadPool freezing after call

### ISSUE THREAD

**Issue by ranis-junior** [GoogleChromeLabs/wasm-bindgen-rayon#22]
I'm trying to make the basic example with the sum function work

```
#[wasm_bindgen]
pub fn sum(numbers: &[i32]) -> i32 {
    numbers.par_iter().sum()
}
```

but every time when JS hit the funcion initThreadPool(even with the init function working correctly), he's freezing, I have tried in two different ways, first

```
init().then(_ => {
    initThreadPool(navigator.hardwareConcurrency).then(_ => {
        sum(new Int32Array([1, 2, 3]))
    })
})
```
and

```
init().then(_ => {
    initThreadPool(navigator.hardwareConcurrency);
    sum(new Int32Array([1, 2, 3]));
})
```

but with that last way, I always get that error: "panicked at 'The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Error { kind: Unsupported, message: "operation not supported on this platform" }) }'", and after a few days I still have no idea what it could be

**Comment by RReverser** [comment]
As shown in README, `initThreadPool` is also asynchronous and you need to wait for it with either `await`:

```js
await init();
await initThreadPool(navigator.hardwareConcurrency);
sum(new Int32Array([1, 2, 3]));
```

or another chained `.then`:

```js
init()
.then(() => initThreadPool(navigator.hardwareConcurrency))
.then(() => {
  sum(new Int32Array([1, 2, 3]));
});
```

**Comment by RReverser** [comment]
Hmm wait you're saying that first example

```js
init().then(_ => {
    initThreadPool(navigator.hardwareConcurrency).then(_ => {
        sum(new Int32Array([1, 2, 3]))
    })
})
```

also didn't work for you?

That one should work. Why do you think it's freezing? Note that you're not writing the output anywhere, did you try adding `console.log` for the result of `sum`?

**Comment by ranis-junior** [comment]
Yes, I have tried with `console.log`, and by adding a breakpoint on JS, both did not work, and console don't show me any clue about that. 
```
<script type="module">
    import init, {sum, initThreadPool} from "/static/pkg/sum.js";

    init().then(_ => {
        initThreadPool(navigator.hardwareConcurrency)
        let result = sum(new Int32Array([1, 2, 3]))
        console.log(result)
    })

</script>
```

I'm trying to do it this way, but the JS never hit the `console.log` line, even if I use `wait`, or `.them`. I tried to put a bunch of alerts on generated JS code, to see what happen, he even call `startWorkers` from workerHelpers.js, but in some point freeze.

**Comment by allsey87** [comment]
I think I had a similar issue and the code was blocking at `wbg_rayon_PoolBuilder::build`, specifically at `build_global`. I added a binding to the JS console so that I could see where it was hanging. Unfortunately, I can't remember the exact details of this problem, although it did seem to be intermittent and adding calls to `console.log` seemed to make it work more consistently which may suggest timing issues.

I think I may have solved this problem by starting with the demo from this project and then incrementally changing it into what I wanted, carefully checking each time to see if I had broken something :P

**Comment by RReverser** [comment]
Very strange. If someone has a repro (maybe try initializing and tearing down a threadpool in a loop?), I'd be happy to take a look, but otherwise hard to tell what's going on.

**Comment by RReverser** [comment]
Btw, any particular browser you've been having issues on or could you reproduce the same across various browsers? Issue description doesn't mention those details.

**Comment by RReverser** [comment]
@ranis-junior Wait a second, so you're trying to use wasm-bindgen generated code directly from HTML, aka from the main thread? Unfortunately that won't work due to Wasm limitations intended to avoid blocking the main thread.

Please check the [Caveats](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon#caveats) section of the docs as well as how the demo does it - you must do all the work in a dedicated Worker.

**Comment by ranis-junior** [comment]
> @ranis-junior Wait a second, so you're trying to use wasm-bindgen generated code directly from HTML, aka from the main thread? Unfortunately that won't work due to Wasm limitations intended to avoid blocking the main thread.
> 
> Please check the [Caveats](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon#caveats) section of the docs as well as how the demo does it - you must do all the work in a dedicated Worker.
> 
> Even if you don't use Comlink, the minimal example should be more like:
> 
> 1. `worker.js`:
> 
> ```js
>     import init, {sum, initThreadPool} from "/static/pkg/sum.js";
> 
>     init().then(_ => {
>         initThreadPool(navigator.hardwareConcurrency).then(_ => {
>             let result = sum(new Int32Array([1, 2, 3]))
>             console.log(result)
>         })
>     })
> ```
> 
> 2. `index.html`:
> 
> ```
> <script type="module">
> new Worker(new URL('worker.js', import.meta.url));
> </script>
> ```
> 
> It's surprising that you didn't see an error message in the Console, both Chrome and Firefox should complain when you're trying to use Wasm threads from the main browser thread.

Yeah, I have tried directly from the main thread, so can be this the problem, I will try to create a worker and see if that solve. But chrome and firefox dont give me that feedback, just the error message `The global thread pool has not been initialized. : operation not supported on this platform`

**Comment by RReverser** [comment]
Ah, not sure, but maybe that `operation not supported on this platform` inner message is how the error ends up looking after being caught.

**Comment by ranis-junior** [comment]
With a dedicated worker and changing the generated JS a little it worked well, ty guys

**Comment by RReverser** [comment]
Glad it worked!
