### ISSUE TITLE
Error: crate directory is missing a `Cargo.toml` file; is `-Z` the wrong directory?

### ISSUE THREAD

**Issue by dimasukr** [GoogleChromeLabs/wasm-bindgen-rayon#26]
Using this command line with latest wasm-pack (and latest nightly):
`wasm-pack build --target web -- -Z build-std=panic_abort,std`
Got this error:
```
Error: crate directory is missing a `Cargo.toml` file; is `-Z` the wrong directory?
```
Adding "." before -Z works:
`wasm-pack build --target web -- . -Z build-std=panic_abort,std`

**Comment by RReverser** [comment]
That's weird. It worked fine in https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/pull/25, including the CI part: https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/runs/6209310561?check_suite_focus=true#step:3:44

The command there is slightly more complicated, but it still omits the directory with no problems.

**Comment by RReverser** [comment]
> and latest nightly

Just to be sure, are you using nightly version recommended in README or actually _latest_? If the latter, there are no guarantees and nightly Rust might have very well broken something.

**Comment by dimasukr** [comment]
It is the latest nightly so not as recommended in README.
Maybe something is broken or just changed there.
I want to put it here in case anyone else runs with into this issue

**Comment by RReverser** [comment]
Message "is `-Z` the wrong directory" seems to suggest that cargo doesn't understand `-Z` anymore, which, if true, is likely to cause problems when we upgrade, yeah. It also suggests that this is indeed due to newer nightly Rust and not due to wasm-pack.

**Comment by ephraimkunz** [comment]
I saw the same issue using either the latest nightly or the nightly specified in the README. @dimasukr's fix of adding the . after the -- fixed it for me.

**Comment by RReverser** [comment]
Hmm @ImUrX did you run into this in your PR?

**Comment by ImUrX** [comment]
No, but I might have skipped something

**Comment by ImUrX** [comment]
Seems I never sent the reply, I don't remember it happening it to me but I might have skipped something, should we change the docs?
