### ISSUE TITLE
Can this package also be used with webpack version 4?

### ISSUE THREAD

**Issue by Nahee-Park** [GoogleChromeLabs/wasm-bindgen-rayon#33]
Hi, I'm attempting to create and use a new rust wasm package for the existing React project.
However, because the React project's bundler is `webpack 4.42.0`, import.meta.url does not operate properly.
It is now difficult to upgrade the project's bundler to `webpack5`.
Would there be a recommended approach to utilize `pub use wasm bindgen rayon::init thread pool;` on `webpack 4.42.0`?

### Version
```
    wasm-bindgen = "0.2.72"
    wasm-bindgen-rayon = { version = "1.0", features = ["no-bundler"] }
```

```
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11",
    "worker-loader": "^2.0.0"
```

**Comment by RReverser** [comment]
Webpack 4.42 is 3 years old. I guess it could work - you're welcome to try - but, personally, I don't have any interest in testing and investing efforts into special support for it.
