### ISSUE TITLE
why not stable?

### ISSUE THREAD

**Issue by mimoo** [GoogleChromeLabs/wasm-bindgen-rayon#34]
Hey!

I was wondering why we can't use Rust stable and have to use Rust nightly. Thanks!

**Comment by RReverser** [comment]
Because, as the README says, it required rebuilding standard library with Wasm atomics support, and that's possible only on nightly Rust. The standard library build provided by stable Rust doesn't support atomics.

**Comment by RReverser** [comment]
FWIW, as I just learnt, you can actually use stable toolchain too if you set RUSTC_BOOTSTRAP=1 env variable during the build. It's not particularly documented or meant to be used for this, but... it might help 😅
