### ISSUE TITLE
Use location.pathname in workerHelper.js instead of URL bundler logic

### ISSUE THREAD

**Issue by codeart1st** [GoogleChromeLabs/wasm-bindgen-rayon#36]
Vite bundler not work with wasm-bindgen-rayon. It fails to build.

```
transforming (337) node_modules/@petamoriken/float16/src/_util/spec.mjsUnexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(vite:worker-import-meta-url) transform "/home/foobar/wgpu-layers/demo/src/OffscreenTileLayer.js"
error during build:
Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(vite:worker-import-meta-url) transform "/home/foobar/wgpu-layers/demo/src/OffscreenTileLayer.js"
    at EventEmitter.handleEmptyEventLoop (file:///home/foobar/wgpu-layers/demo/node_modules/rollup/dist/es/shared/rollup.js:24061:20)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:525:35)
    at process.<anonymous> (file:///home/foobar/wgpu-layers/demo/node_modules/rollup/dist/es/shared/rollup.js:24055:55)
    at process.emit (node:events:513:28)
```

Probably it's a bug in vite, but I try to find a workaround for it. The problem seems to be the workerHelper.js
https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/blob/c3a12c4843b35d5c528fbed178aad1e9142c8072/src/workerHelpers.js#L99-L101
It seems to be that vite don't like the recursive bundling part.

My workaround for now is the following:
```
const worker = new Worker(location.pathname);
```
This works pretty well. And should work for all environments instead of inlining worker code in the main bundle. This use case should not work anymore with this approach.

**Comment by codeart1st** [comment]
Seems to be not a good solution. It breaks vite's dev mode and maybe webpack's too.

**Comment by RReverser** [comment]
Vite uses esbuild, right? If so, unfortunately that's a long-standing feature request on which I commented at some time but obviously couldn't affect its implementation progress otherwise. https://github.com/evanw/esbuild/issues/312

**Comment by codeart1st** [comment]
Yeah, @esbuild is part of my node_modules folder. I will look into your linked esbuild issues. Ty 👍
