### ISSUE TITLE
RuntimeError: unreachable in webworker when use a lot of memory

### ISSUE THREAD

**Issue by zhangyuang** [GoogleChromeLabs/wasm-bindgen-rayon#38]
In below code

```rust
mod utils;
use utils::set_panic_hook;
use wasm_bindgen::prelude::*;

// When the `wee_alloc` feature is enabled, use `wee_alloc` as the global
// allocator.
#[cfg(feature = "wee_alloc")]
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;
use js_sys::{JsString, Reflect, Uint8Array};

#[cfg(feature = "parallel")]
pub use wasm_bindgen_rayon::init_thread_pool;

#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

macro_rules! console_log {
($($t:tt)*) => (log(&format_args!($($t)*).to_string()))
}


#[wasm_bindgen]
pub fn test_return_string() -> JsString {
    use serde::{Deserialize, Serialize};

    #[derive(Debug, Serialize, Deserialize, Clone)]
    struct Foo {
        a: String,
    }
    let foo = Foo { a: "".to_string() };
    let mut v = "".to_string();

    for i in 0..10 {
        console_log!("{}", i);
        let bar = vec![&foo; 10000000];
        // console_log!("bar size{}", std::mem::size_of_val(&*bar));
        let bar2 = serde_json::to_string(&bar).unwrap();
        v.push_str(bar2.as_str());
        console_log!("v size{}", std::mem::size_of_val(&*v));

    }
    return v.into()
}

```
It's my build script
```js
    "dev:build:mt": " RUSTFLAGS=\"-C target-feature=+atomics,+bulk-memory,+mutable-globals\" wasm-pack build  ./packages/wasm --target web --out-dir ../../example/pkg-mt -- --features parallel -Z build-std=panic_abort,std ",

```

there code will be executed error when use sharedArrayBuffer in webworker.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/17424434/216923445-a58e00d0-c2fc-408f-9c91-536d1cfed4db.png">

If i run it in main thread it can be succeed.I guess the error caused by allocate memory

**Comment by RReverser** [comment]
It could be that browsers just allow less memory for the Web Workers. I don't see evidence that this is particularly wasm-bindgen-rayon issue tbh.

**Comment by RReverser** [comment]
As per above, I think I'm going to close this since it seems like a general JS or browser issue rather than something to do with Rayon or wasm-bindgen-rayon. Feel free to comment with more details if this conclusion is wrong.

**Comment by zhangyuang** [comment]
emmmm🤔，But if i don't use rayon to generate bridge code about sharedArrayBuffer like

```js
function initMemory(imports, maybe_memory) {
    imports.wbg.memory = maybe_memory || new WebAssembly.Memory({initial:18,maximum:16384,shared:true});
}
```
It can be execued succeed.

**Comment by zhangyuang** [comment]
emmm，But the struct used memory is no more than the webworker memory limit。As the above bridge wasm code

```js
function initMemory(imports, maybe_memory) {
    imports.wbg.memory = maybe_memory || new WebAssembly.Memory({initial:18,maximum:16384,shared:true});
}
```
The max memory is `1GB`, it's where I'm confused

**Comment by RReverser** [comment]
> The max memory is `1GB`, it's where I'm confused

Ah that JS is generated by wasm-bindgen itself and not something I can control from the library.

Sounds like you might want to raise an issue on the wasm-bindgen repo. I agree 1GB limit might be a bit low sometimes. I guess they wanted to accommodate devices with low memory capacity, so perhaps this max limit needs to be configurable like it is in Emscripten.
