### ISSUE TITLE
Use rayon par_iter() in wasm multiply threads by webworker throw error memory access out of bounds

### ISSUE THREAD

**Issue by zhangyuang** [GoogleChromeLabs/wasm-bindgen-rayon#40]
Reproducion code

```js
#[derive(Debug, Serialize, Deserialize, Clone)]
    pub struct Node {
        pub nt: String,   // node_type
        pub name: String, // name
        pub id: usize,    // id
        pub size: usize,  // self_size
        #[serde(skip_serializing)]
        pub ec: usize, // edge_count
        // pub trace_node_id: JsValueType,
        pub rs: usize, // retained_size
        pub edges: Vec<Edge>,
        pub p: Vec<usize>,
        pub c: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub se: Option<String>, // source
    }

  use rayon::prelude::*;
    let v:Vec<Node> = (0..1000000).into_par_iter().map(|_| {
        let node = Node {
            nt: "1".to_string(),
            id: 1,
            ec: 1,
            edges: vec![],
            se: None,
            size: 1,
            name: "1".to_string(),
            p: vec![],
            rs: 1,
            c: "1".to_string(),
        };
       node
    }).collect();
    let str = serde_json::to_string(&v).unwrap();
    return str;

```
<img width="575" alt="image" src="https://user-images.githubusercontent.com/17424434/228225218-5d3fa9af-d9d3-45ff-bfe1-0dab0e547da5.png">

**Comment by RReverser** [comment]
Hm, hard to say what's going on tbh. Can you try putting repro code in a repo so that I could see all the configs & easily build with same steps via `wasm-pack` on that repo?

**Comment by zhangyuang** [comment]
yeah, Wait a minute

**Comment by RReverser** [comment]
Btw you might also want to build with wasm-pack --profiling - that will preserve function names so you at least know where it throws. Or just debug mode is fine too.

**Comment by zhangyuang** [comment]
https://github.com/zhangyuang/rayon-bug-wasm/blob/master/src/lib.rs#L23
https://github.com/zhangyuang/rayon-bug-wasm/blob/master/wasm-worker.js#L9

It's reproduction repo from official demo。 I mark which code fragment has been changed.

**Comment by zhangyuang** [comment]
When i change `into_par_iter` to `into_iter` it can be executed succeed

**Comment by RReverser** [comment]
That repo doesn't build at the moment and is missing lots of configs; please make sure it actually builds with `wasm-pack build`:

```
Error: `cargo metadata` exited with an error: error: failed to parse manifest at `/home/rreverser/rayon-bug-wasm/Cargo.toml`

Caused by:
  feature `parallel` includes `rayon`, but `rayon` is not an optional dependency
  A non-optional dependency of the same name is defined; consider adding `optional = true` to its definition.

Caused by: `cargo metadata` exited with an error: error: failed to parse manifest at `/home/rreverser/rayon-bug-wasm/Cargo.toml`

Caused by:
  feature `parallel` includes `rayon`, but `rayon` is not an optional dependency
  A non-optional dependency of the same name is defined; consider adding `optional = true` to its definition.
```

**Comment by zhangyuang** [comment]
excuse me，the source repo is complicated，the simpleness reproduction repo from official repo which i will complete it tomorrow

**Comment by zhangyuang** [comment]
The reproduction repo has been updated, you can run below command for reproduce

```bash
$ git clone git@github.com:zhangyuang/rayon-bug-wasm.git
$ yarn global add serve
$ yarn && yarn build && serve ./dist
$ open http://localhost:3000
```
And then click the button that you can see the error in console
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/17424434/228453049-d5d18642-cf03-400d-9043-b7bb8972eece.png">
For comparison i find the reason cause error is `WeeAlloc`

```rust
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;
```
When i remove WeeAlloc it can be executed succeed, but i find another problem is `into_par_iter` is too slowly than `into_iter` in this demo。Can you help me find the reason?

**Comment by zhangyuang** [comment]
Thanks a lot！

**Comment by zhangyuang** [comment]
Reopen it, The demo in my intel macbooks and windows, `into_par_iter` is also slower than `into_iter` 🤔
 
<img width="537" alt="image" src="https://user-images.githubusercontent.com/17424434/230715109-8e7338ed-6feb-4a9e-a712-cbce063a8c1a.png">

**Comment by zhangyuang** [comment]
I guess whether in big struct memory scene `into_par_iter `  is slower than `into_iter`  when compile to wasm

**Comment by RReverser** [comment]
Weird, first time I hear about issues on other CPUs. Do you see the same on the original demo (https://rreverser.com/wasm-bindgen-rayon-demo/)?

**Comment by RReverser** [comment]
Although, if it's just on your demo - is it this one still? https://github.com/zhangyuang/rayon-bug-wasm/blob/c3582ecbc0301da29a7c11050cd27fbcddda29b4/src/lib.rs#L62-L77 - I think that's expected.

Your parallel part of the code is currently not doing any real work - it's just creating structs - so what you're observing is likely the pure overhead of collecting structs from a bunch of different threads and copying them around to the main thread's final `Vec`. That's not where multithreading shines.

**Comment by zhangyuang** [comment]
the original demo is expected but the demo i provide is unexpected

**Comment by zhangyuang** [comment]
In production code，the struct has been generated by some calculates。I guess the overhead of copy struct is more than calculate performance

**Comment by zhangyuang** [comment]
I use sharedArraybuffer for avoid copy memory。why there has memory copy between main thread and child thread？

**Comment by RReverser** [comment]
> why there has memory copy between main thread and child thread？

Not exactly between threads, but your structs are created individually and then need to be copied in the correct order into a Vec when collecting. This usually will be cheap, but if it's basically the only thing you're measuring, then yeah, it will appear slower than creating everything in-place without several threads having to copy into the same Vec and in the right order.

**Comment by zhangyuang** [comment]
In production, the struct fields has been calculated like below code

```js
let node = Node {
            nt:  calculate_nt(),
            id: calculate_id(),
            ec: calculate_ec(),
            // xxx
        };
```
Are there any ways improve performance? 

In rust binary file, use rayon optimization has higher performance but in browser wasm is slower

**Comment by RReverser** [comment]
I don't know, it's hard to tell without deeper looking at your code but that's something you'll have to dig in yourself. Is the difference big? If your original code is already very fast, it's possible that overhead of multithreading is still dominating the performance.

**Comment by RReverser** [comment]
I'm going to close this back as the original issue turned out to be due to wee-alloc not this library.
