### ISSUE TITLE
TypeError: error loading dynamically imported module

### ISSUE THREAD

**Issue by mtb0x1** [GoogleChromeLabs/wasm-bindgen-rayon#41]
I am currently facing an error when I try to execute a code that uses `wasm-bindgen-rayon`.
I am using Firefox v116.x with `hardwareConcurrency` activated and I followed the instructions as provided in this repo. (except the dependencies versions, I tested with the ones specified in the Readme and same result) 
Also I made sure the COOP and COEP in my [webserver](https://github.com/mtb0x1/llama2.rs.wasm/blob/main/port1/www/www_server.py).

my code is available [here](https://github.com/mtb0x1/llama2.rs.wasm/tree/main/port1), when I activate the [`initThreadPool`](https://github.com/mtb0x1/llama2.rs.wasm/blob/65d7210ba9508d3d5cc2dc1b2abaaf969baebbd7/port1/www/index.html#L73)

1. It fetches worker.js N times 
![image](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/assets/39337159/c489d0c0-a9c0-4ad6-b536-a818eeaba663)
2. But fails to activate the module with this same error N times.
![image](https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/assets/39337159/133fcfab-deda-4db3-921d-a89af1657f24)

(without `initThreadPool` call everything works as I expect it)

Any idea on how to debug this or the source of issue ?

Thanks.

**Comment by RReverser** [comment]
I was going to say something clearly looks wrong as in your screenshot I see workerHelpers.js instead of workerHelpers.no-bundler.js, but I see you found the `no-bundler` feature and added it since posting this issue. Did it help?

**Comment by mtb0x1** [comment]
Yes, it did in a way. I don't have the initial error, but I am facing another issue as it seems :  ```Uncaught TypeError: waiting is not allowed on this thread```

The code looks like this now : 
```js
import init, { main_wasm, initThreadPool  } from './pkg/port1.js';
await init();
await initThreadPool(navigator.hardwareConcurrency);

async function run() { 
     ... 
    main_wasm(...)
}
document.getElementById('run').addEventListener('click', run);

````

**Comment by RReverser** [comment]
> but I am facing another issue as it seems : `Uncaught TypeError: waiting is not allowed on this thread`

Yup, that's a different issue, it's described in README. Basically you have to run your Wasm in a Worker yourself unfortunately :(
