### ISSUE TITLE
Rustflags now require alsow +mutable-globals

### ISSUE THREAD

**Issue by Ciantic** [GoogleChromeLabs/wasm-bindgen-rayon#9]
I spent quiet some time wondering about linker errors, looks like RUSTFLAGS with latest nightly needs also mutable-globals, e.g.

```
-C target-feature=+atomics,+bulk-memory,+mutable-globals
```

See e.g. https://github.com/rustwasm/wasm-bindgen/issues/2487 and the appropriate fix https://github.com/alexcrichton/wasm-bindgen/commit/ad53c1223a09029b533bdbcc98be5d07a12da71a

**Comment by RReverser** [comment]
>  looks like RUSTFLAGS with latest nightly needs also mutable-globals,

Yeah those things tend to change / break over time which is why the README specifically recommends a fixed nightly version. I suppose we can upgrade that version at some point + update the required flags though.

**Comment by RReverser** [comment]
Actually, if you can find a nightly hash that corresponds to latest stable Rust (we do this to reduce risks), I'd be happy to accept a PR that updates the Rust version & required features.
